In [2]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd

In [3]:
from keras.datasets import mnist

In [4]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()

In [5]:
print(x_train.shape)
print(x_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [6]:
x_train = np.array(x_train)
x_train = x_train.reshape(60000,784)
x_train = tf.cast(x_train, tf.float32)

In [7]:
x_test = np.array(x_test)
x_test = x_test.reshape(10000,784)
x_test.shape

(10000, 784)

In [8]:
df = pd.DataFrame(y_train)
df

0
0      5
1      0
2      4
3      1
4      9
...   ..
59995  8
59996  3
59997  5
59998  6
59999  8

[60000 rows x 1 columns]

In [9]:
 
y_train= pd.get_dummies(df, columns = [0]) 
print(y_train)
y_train = y_train.astype(int)
print(y_train)

         0_0    0_1    0_2    0_3    0_4    0_5    0_6    0_7    0_8    0_9
0      False  False  False  False  False   True  False  False  False  False
1       True  False  False  False  False  False  False  False  False  False
2      False  False  False  False   True  False  False  False  False  False
3      False   True  False  False  False  False  False  False  False  False
4      False  False  False  False  False  False  False  False  False   True
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
59995  False  False  False  False  False  False  False  False   True  False
59996  False  False  False   True  False  False  False  False  False  False
59997  False  False  False  False  False   True  False  False  False  False
59998  False  False  False  False  False  False   True  False  False  False
59999  False  False  False  False  False  False  False  False   True  False

[60000 rows x 10 columns]
       0_0  0_1  0_2  0_3  0_4  0_5  0_6  0_7  0_8  0_9
0    

In [10]:
dft = pd.DataFrame(y_test)
dft

0
0     7
1     2
2     1
3     0
4     4
...  ..
9995  2
9996  3
9997  4
9998  5
9999  6

[10000 rows x 1 columns]

In [11]:
y_test= pd.get_dummies(dft, columns= [0])
print(y_test)
y_test = y_test.astype(int)
print(y_test)

        0_0    0_1    0_2    0_3    0_4    0_5    0_6    0_7    0_8    0_9
0     False  False  False  False  False  False  False   True  False  False
1     False  False   True  False  False  False  False  False  False  False
2     False   True  False  False  False  False  False  False  False  False
3      True  False  False  False  False  False  False  False  False  False
4     False  False  False  False   True  False  False  False  False  False
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
9995  False  False   True  False  False  False  False  False  False  False
9996  False  False  False   True  False  False  False  False  False  False
9997  False  False  False  False   True  False  False  False  False  False
9998  False  False  False  False  False   True  False  False  False  False
9999  False  False  False  False  False  False   True  False  False  False

[10000 rows x 10 columns]
      0_0  0_1  0_2  0_3  0_4  0_5  0_6  0_7  0_8  0_9
0       0    0    

In [12]:
n_input = 784
n_h1 = 392
n_h2 = 196
n_out = 10

In [13]:
weights = {
    'h1' : tf.random.uniform([n_input,n_h1],minval=-1.0,maxval=1.0),
    'h2' : tf.random.uniform([n_h1,n_h2],minval=-1.0,maxval=1.0),
    'out' : tf.random.uniform([n_h2,n_out],minval=-1.0,maxval=1.0)
}

bias = {
    'h1' : tf.random.uniform([n_h1],minval=-1.0,maxval=1.0),
    'h2' : tf.random.uniform([n_h2],minval=-1.0,maxval=1.0),
    'out' : tf.random.uniform([n_out],minval=-1.0,maxval=1.0)
}

In [14]:
def forwardpropogation(x,weights,bias):
    in_layer1 = tf.add(tf.matmul(x,weights['h1']),bias['h1'])
    out_layer1 = tf.nn.relu(in_layer1)

    in_layer2 = tf.add(tf.matmul(out_layer1,weights['h2']),bias['h2'])
    out_layer2 = tf.nn.relu(in_layer2)

    output = tf.add(tf.matmul(out_layer2,weights['out']),bias['out'])

    return output

In [15]:
y_pred = forwardpropogation(x_train,weights,bias)
y_pred = tf.argmax(y_pred,1)
y_pred = tf.cast(y_pred, dtype=tf.float32)
y_train = tf.argmax(y_train,1)
y_train = tf.cast(y_train, dtype=tf.float32)
y_pred,y_train

(<tf.Tensor: shape=(60000,), dtype=float32, numpy=array([5., 5., 0., ..., 5., 5., 5.], dtype=float32)>,
 <tf.Tensor: shape=(60000,), dtype=float32, numpy=array([5., 0., 4., ..., 5., 6., 8.], dtype=float32)>)

In [16]:
correct_pred = tf.equal(y_pred,y_train)
count = 0
correct_pred

<tf.Tensor: shape=(60000,), dtype=bool, numpy=array([ True, False, False, ...,  True, False, False])>

In [17]:
correct_pred_np = correct_pred.numpy()
print(correct_pred_np)
print(correct_pred_np[0])

for e in correct_pred_np:
    if(e == 'True'):
        print('1')

[ True False False ...  True False False]
True


In [18]:
type(correct_pred_np)

numpy.ndarray

In [19]:
sum_correct_pred = tf.reduce_sum(tf.cast(correct_pred, dtype=tf.int32))
print(sum_correct_pred)

tf.Tensor(6880, shape=(), dtype=int32)


In [21]:
error = tf.nn.softmax_cross_entropy_with_logits(labels=y_train,logits=y_pred)
error

<tf.Tensor: shape=(), dtype=float32, numpy=3362985.0>

In [47]:
trainable_vars = [weights['h1'],bias['h1'],weights['h2'],bias['h2'],weights['out'],bias['out']]
trainable_vars
trainable_vars1 = [weights,bias]
trainable_vars1

[{'h1': <tf.Tensor: shape=(784, 392), dtype=float32, numpy=
  array([[-0.33704638,  0.4691062 ,  0.20533013, ...,  0.6025193 ,
          -0.3183782 , -0.60153556],
         [ 0.67788005,  0.04707813,  0.1423192 , ..., -0.25594616,
          -0.35294318, -0.43114758],
         [-0.592566  , -0.41960979, -0.6248834 , ..., -0.02429056,
           0.591661  , -0.6601517 ],
         ...,
         [ 0.15508318, -0.08495307, -0.57480764, ...,  0.12809825,
          -0.5421853 ,  0.72237444],
         [-0.23559332,  0.52002907,  0.24465942, ...,  0.79031134,
          -0.68506765,  0.8047364 ],
         [-0.29866552, -0.89156675,  0.04043484, ..., -0.25790906,
           0.45103693,  0.7264869 ]], dtype=float32)>,
  'h2': <tf.Tensor: shape=(392, 196), dtype=float32, numpy=
  array([[-0.21190596, -0.57082915, -0.4147687 , ..., -0.640692  ,
           0.02685237, -0.46231604],
         [-0.69732   , -0.21929288, -0.37001038, ...,  0.17741585,
          -0.4143219 ,  0.537276  ],
         [ 0.406

In [34]:
# optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)
# epochs = 10

# for epoch in range(epochs):
#     with tf.GradientTape() as tape:
#         # Forward pass
#         y_pred = forwardpropogation(x_train,weights,bias)
#         y_pred = tf.argmax(y_pred,1)
#         y_pred = tf.cast(y_pred, dtype=tf.float32)
        
#         # Calculate the error using softmax_cross_entropy_with_logits
#         error = tf.nn.softmax_cross_entropy_with_logits(labels=y_train, logits=y_pred)
#         loss = tf.reduce_mean(error)

#     # Compute gradients and apply them using the optimizer
#     gradients = tape.gradient(loss,trainable_variables)
#     optimizer.apply_gradients(zip(gradients,trainable_variables))

#     print(f'Epoch {epoch + 1}, Loss: {loss.numpy()}')

In [50]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)
optimize = optimizer.minimize(error,var_list = trainable_vars)

ValueError: `tape` is required when a `Tensor` loss is passed. Received: loss=3362985.0, tape=None.

In [48]:
epochs = 100 #(or however many iterations you want it to run)
for _ in range(epochs):
    with tf.GradientTape() as tp:
        #your loss/cost function must always be contained within the gradient tape instantiation
        cost_fn = tf.nn.softmax_cross_entropy_with_logits(labels=y_train, logits=y_pred)
    gradients = tp.gradient(cost_fn, trainable_vars)
    optimizer.apply_gradients(zip(gradients, trainable_vars))

AttributeError: Tensor.name is undefined when eager execution is enabled.