In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd

In [2]:
from keras.datasets import mnist

In [3]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()

In [4]:
print(x_train.shape)
print(x_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [5]:
x_train = np.array(x_train)
x_train = x_train.reshape(60000,784)
x_train = tf.cast(x_train, tf.float32)

In [6]:
x_test = np.array(x_test)
x_test = x_test.reshape(10000,784)
x_test.shape

(10000, 784)

In [7]:
df = pd.DataFrame(y_train)
df

0
0      5
1      0
2      4
3      1
4      9
...   ..
59995  8
59996  3
59997  5
59998  6
59999  8

[60000 rows x 1 columns]

In [8]:
 
y_train= pd.get_dummies(df, columns = [0]) 
print(y_train)
y_train = y_train.astype(int)
print(y_train)

         0_0    0_1    0_2    0_3    0_4    0_5    0_6    0_7    0_8    0_9
0      False  False  False  False  False   True  False  False  False  False
1       True  False  False  False  False  False  False  False  False  False
2      False  False  False  False   True  False  False  False  False  False
3      False   True  False  False  False  False  False  False  False  False
4      False  False  False  False  False  False  False  False  False   True
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
59995  False  False  False  False  False  False  False  False   True  False
59996  False  False  False   True  False  False  False  False  False  False
59997  False  False  False  False  False   True  False  False  False  False
59998  False  False  False  False  False  False   True  False  False  False
59999  False  False  False  False  False  False  False  False   True  False

[60000 rows x 10 columns]
       0_0  0_1  0_2  0_3  0_4  0_5  0_6  0_7  0_8  0_9
0    

In [9]:
dft = pd.DataFrame(y_test)
dft

0
0     7
1     2
2     1
3     0
4     4
...  ..
9995  2
9996  3
9997  4
9998  5
9999  6

[10000 rows x 1 columns]

In [10]:
y_test= pd.get_dummies(dft, columns= [0])
print(y_test)
y_test = y_test.astype(int)
print(y_test)

        0_0    0_1    0_2    0_3    0_4    0_5    0_6    0_7    0_8    0_9
0     False  False  False  False  False  False  False   True  False  False
1     False  False   True  False  False  False  False  False  False  False
2     False   True  False  False  False  False  False  False  False  False
3      True  False  False  False  False  False  False  False  False  False
4     False  False  False  False   True  False  False  False  False  False
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
9995  False  False   True  False  False  False  False  False  False  False
9996  False  False  False   True  False  False  False  False  False  False
9997  False  False  False  False   True  False  False  False  False  False
9998  False  False  False  False  False   True  False  False  False  False
9999  False  False  False  False  False  False   True  False  False  False

[10000 rows x 10 columns]
      0_0  0_1  0_2  0_3  0_4  0_5  0_6  0_7  0_8  0_9
0       0    0    

In [11]:
n_input = 784
n_h1 = 392
n_h2 = 196
n_out = 10

In [12]:
weights = {
    'h1' : tf.random.uniform([n_input,n_h1],minval=-1.0,maxval=1.0),
    'h2' : tf.random.uniform([n_h1,n_h2],minval=-1.0,maxval=1.0),
    'out' : tf.random.uniform([n_h2,n_out],minval=-1.0,maxval=1.0)
}

bias = {
    'h1' : tf.random.uniform([n_h1],minval=-1.0,maxval=1.0),
    'h2' : tf.random.uniform([n_h2],minval=-1.0,maxval=1.0),
    'out' : tf.random.uniform([n_out],minval=-1.0,maxval=1.0)
}

In [13]:
def forwardpropogation(x,weights,bias):
    in_layer1 = tf.add(tf.matmul(x,weights['h1']),bias['h1'])
    out_layer1 = tf.nn.relu(in_layer1)

    in_layer2 = tf.add(tf.matmul(out_layer1,weights['h2']),bias['h2'])
    out_layer2 = tf.nn.relu(in_layer2)

    output = tf.add(tf.matmul(out_layer2,weights['out']),bias['out'])

    return output

In [14]:
y_pred = forwardpropogation(x_train,weights,bias)
y_pred = tf.argmax(y_pred,1)
y_pred = tf.cast(y_pred, dtype=tf.float32)
y_train = tf.argmax(y_train,1)
y_train = tf.cast(y_train, dtype=tf.float32)
y_pred,y_train

(<tf.Tensor: shape=(60000,), dtype=float32, numpy=array([9., 8., 3., ..., 9., 9., 8.], dtype=float32)>,
 <tf.Tensor: shape=(60000,), dtype=float32, numpy=array([5., 0., 4., ..., 5., 6., 8.], dtype=float32)>)

In [15]:
correct_pred = tf.equal(y_pred,y_train)
count = 0
correct_pred

<tf.Tensor: shape=(60000,), dtype=bool, numpy=array([False, False, False, ..., False, False,  True])>

In [16]:
correct_pred_np = correct_pred.numpy()
print(correct_pred_np)
print(correct_pred_np[0])

for e in correct_pred_np:
    if(e == 'True'):
        print('1')

[False False False ... False False  True]
False


In [17]:
type(correct_pred_np)

numpy.ndarray

In [18]:
sum_correct_pred = tf.reduce_sum(tf.cast(correct_pred, dtype=tf.int32))
print(sum_correct_pred)

tf.Tensor(7480, shape=(), dtype=int32)


In [19]:
error = tf.nn.softmax_cross_entropy_with_logits(labels=y_train,logits=y_pred)
error

<tf.Tensor: shape=(), dtype=float32, numpy=3373749.5>

In [20]:
trainable_vars = [weights['h1'],bias['h1'],weights['h2'],bias['h2'],weights['out'],bias['out']]
trainable_vars
trainable_vars1 = [weights,bias]
trainable_vars1

[{'h1': <tf.Tensor: shape=(784, 392), dtype=float32, numpy=
  array([[ 0.55316687, -0.18975711, -0.3243544 , ..., -0.56612444,
          -0.61613417,  0.7041285 ],
         [-0.02297735, -0.28982353, -0.06136131, ...,  0.83217645,
          -0.19346213,  0.32695007],
         [ 0.93679476,  0.7397816 , -0.7020376 , ...,  0.33782744,
          -0.2790575 , -0.06544471],
         ...,
         [-0.02692389,  0.528162  ,  0.1056366 , ..., -0.00318789,
           0.2407453 ,  0.56764245],
         [ 0.8891001 ,  0.22902417,  0.3304875 , ...,  0.97950554,
          -0.8793185 ,  0.1107285 ],
         [ 0.9245982 , -0.13502598,  0.43909192, ..., -0.7057526 ,
           0.33616185, -0.8819368 ]], dtype=float32)>,
  'h2': <tf.Tensor: shape=(392, 196), dtype=float32, numpy=
  array([[ 0.10618043, -0.45263052, -0.384228  , ...,  0.50216603,
          -0.98257494, -0.11875248],
         [-0.9691148 ,  0.960351  , -0.3299961 , ...,  0.9437356 ,
           0.9392078 , -0.8142402 ],
         [ 0.884

In [21]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

# Training loop
epochs = 10

for epoch in range(epochs):
    with tf.GradientTape() as tape:
        y_pred = forwardpropogation(x_train,weights,bias)
        error = tf.nn.softmax_cross_entropy_with_logits(labels=y_train, logits=y_pred)
        loss = tf.reduce_mean(error)

    # Compute gradients
    gradients = tape.gradient(loss, list(weights.values()) + list(bias.values()))

    # Apply gradients
    optimizer.apply_gradients(zip(gradients, list(weights.values()) + list(bias.values())))

    # Calculate new predictions and accuracy
    y_pred_new = forwardpropogation(x_train,weights,bias)
    correct_pred_new = tf.equal(y_pred_new, y_train)
    sum_correct_pred_new = tf.reduce_sum(tf.cast(correct_pred_new, dtype=tf.int32))

    print(f'Epoch {epoch + 1}, Loss: {loss.numpy()}, Accuracy: {sum_correct_pred_new.numpy() / len(y_train)}')

InvalidArgumentError: {{function_node __wrapped__SoftmaxCrossEntropyWithLogits_device_/job:localhost/replica:0/task:0/device:CPU:0}} logits and labels must be broadcastable: logits_size=[60000,10] labels_size=[1,60000] [Op:SoftmaxCrossEntropyWithLogits] name: 